.PHONY: sum is_prime game_of_life

sum: sum.c
	gcc-15 -O3 -fopenmp -o sum sum.c

is_prime: is_prime.c
	gcc-15 -O3 -fopenmp -o is_prime is_prime.c

game_of_life: game_of_life.c
	gcc-15 -O3 -fopenmp -o game_of_life game_of_life.c